#!/usr/bin/php
<?php

function msg($phase, $msg) {
    echo "\e[1m$phase: $msg\e[m\n";
}
function cmd($cmd) {
    $result = trim(`rhio localhost $cmd`);
    echo "$result\n";
}
function yesno()
{
    while (true) {
        $m = trim(readline());
        if ($m == 'y') return true;
        if ($m == 'n') return false;
        echo "> You should answer 'y' or 'n'\n";
    }
}

msg('CHECK', 'Running a check');
cmd('rhalCheck');

msg('INIT', 'Press enter to run the walk');
readline();
cmd('walk');

msg('ATTACKHERE', 'Put me on the field, facing the opponent goals');
readline();
cmd('attackHere');

msg('CONFIG', 'Am I a goal keeper?');
if (yesno()) {
    cmd('/moves/robocup/goalKeeper=1');
    cmd('/moves/robocup/freeKicker=0');
} else {
    cmd('/moves/robocup/goalKeeper=0');
    
    msg('CONFIG', 'Am I the free kicker?');
    if (yesno()) {
        cmd('/moves/robocup/freeKicker=1');
    } else {
        cmd('/moves/robocup/freeKicker=0');
    }
}

msg('CONFIG', 'Am I auto placing?');
if (yesno()) {
    cmd('/moves/robocup/autoKickOff=1');
} else {
    cmd('/moves/robocup/autoKickOff=0');
}

msg('CONFIG', 'TODO: Commands to choose where I should be placed!');

msg('INFO', 'Checking team radius');
cmd('/moves/approach/teamRadius');

msg('INFO', 'Checking that there is info from the referee');
$r = cmd('playing');
if (strpos($r, 'Referee time: -1') !== false) {

}
