server:
     mode : fake
     port : 7777
     stm_server_path : '../../../Edu/sdk/python/stm/stm_server_main.py'
     python_cmd : 'python3'
     command_store : '../../../Boards/Rhoban.Communication/commands.xml'

