server:
    stm_server_path: /home/rhoban/Edu/sdk/python/stm/stm_server_main.py
    command_store: /home/rhoban/Edu/sdk/common/commands.xml

lowlevel:
    mode: serial

serial:
    device: /dev/maple

