server:
     mode : fake
     port : 7777
     stm_server_path : 'C:\Users\Hugo\Documents\GitHub\Edu\sdk\python\stm\stm_server_main.py'
     command_store : 'C:\Users\Hugo\Documents\GitHub\Boards\Rhoban.Communication\commands.xml'

